
import 'package:flutter/material.dart';

void main() {
  runApp(const SingleChild());
}

class SingleChild extends StatelessWidget {
  const SingleChild({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title:  Text(
            'التصفح العمودي والأفقي',
            textAlign: TextAlign.right,
          ),
          backgroundColor: const Color.fromARGB(255, 63, 184, 109),
        ),
        body: SingleChildScrollView(
          // يجعل النصوص والصفوف للجهة اليمنى

            child: SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              child: Column(
                children: [
                  Row(
                    children: [
                      Column(
                        children: [
                          Row(
                            children: [
                              Column(
                                children:  [
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                ],
                              ),
                              Column(
                                children:  [
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                ],
                              ),
                              // أكمل باقي الأعمدة بنفس الطريقة
                              Column(
                                children:  [
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                ],
                              ),Column(
                                children:  [
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                ],
                              ),Column(
                                children:  [
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                  Text('هذا نص 1'),
                                ],
                              ),
                            ],
                          ),
                          // أكمل باقي الصفوف بنفس الطريقة
        Row(
          children: [
            Column(
              children:  [
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
              ],
            ),
            Column(
              children:  [
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
              ],
            ),Column(
              children:  [
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
              ],
            ),Column(
              children:  [
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
              ],
            ),Column(
              children:  [
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
              ],
            ),Column(
              children:  [
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
              ],
            ),Column(
              children:  [
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
              ],
            ),Column(
              children:  [
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
              ],
            ),Column(
              children:  [
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
              ],
            ),Column(
              children:  [
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
              ],
            ),Column(
              children:  [
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
              ],
            ),Column(
              children:  [
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
                Text('هذا نص 1'),
              ],
            ),
            ]
        ),
                          Row(
                              children: [
                                Column(
                                  children:  [
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                  ],
                                ),
                                Column(
                                  children:  [
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                  ],
                                ),Column(
                                  children:  [
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                  ],
                                ),Column(
                                  children:  [
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                  ],
                                ),Column(
                                  children:  [
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                  ],
                                ),Column(
                                  children:  [
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                  ],
                                ),Column(
                                  children:  [
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                  ],
                                ),Column(
                                  children:  [
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                  ],
                                ),Column(
                                  children:  [
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                  ],
                                ),Column(
                                  children:  [
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                  ],
                                ),Column(
                                  children:  [
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                  ],
                                ),Column(
                                  children:  [
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                    Text('هذا نص 1'),
                                  ],
                                ),
                              ]
                          )
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ),
        ),
      );

  }
}